# Generated by Django 6.1.1 on 2026-09-26 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('orden', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(max_length=128, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('racha_actual', models.PositiveIntegerField(default=0)),
                ('racha_maxima', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Sena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=150)),
                ('video_url', models.URLField()),
                ('validado_por', models.CharField(blank=True, help_text='Nombre de la persona sorda o intérprete certificado que validó esta seña.', max_length=150, null=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senas', to='aprendizaje.modulo')),
            ],
            options={
                'verbose_name': 'Seña',
                'verbose_name_plural': 'Señas',
            },
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('video_a_palabra', 'Ver video, elegir palabra'), ('palabra_a_video', 'Ver palabra, elegir video'), ('orden_pasos', 'Reconstruir orden de los pasos')], max_length=20)),
                ('contenido_json', models.JSONField()),
                ('sena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='aprendizaje.sena')),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
            },
        ),
        migrations.CreateModel(
            name='ProgresoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('intentos', models.PositiveIntegerField(default=1)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='aprendizaje.ejercicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='aprendizaje.usuario')),
            ],
            options={
                'verbose_name': 'Progreso de usuario',
                'verbose_name_plural': 'Progresos de usuario',
                'ordering': ['-fecha'],
            },
        ),
    ]
